### ISSUE TITLE
Change priority?

### ISSUE THREAD

**Issue by cj** [neoclide/coc-tabnine#1]
First off -- thank you for this plugin!

Would it be possible to add a config setting to change priority?  I'm trying to make https://github.com/neoclide/coc-tsserver have higher priority to Tabnine.

Cheers!

**Comment by cj** [comment]
@chemzqm thank you for adding this!

I might be doing something wrong or does https://github.com/neoclide/coc-tsserver also need a priority config for it to work?  I have tried different priorities even `"tabnine.priority": 0` but Tabnine still shows before https://github.com/neoclide/coc-tsserver.

![Image 2019-06-30 at 11 14 55 am](https://user-images.githubusercontent.com/1819/60455977-8f04d300-9bfd-11e9-996a-3af412749b13.png)

**Comment by chemzqm** [comment]
It has higher match score, so it's expected.

**Comment by trygveaa** [comment]
Why does it have a higher match score? Is there no way to make tabnine appear below tsserver (and other language specific results)? The reason I (also) want tsserver first is that the completions from that includes documentation, while tabnine doesn't.

**Comment by rjshrjndrn** [comment]
in `:cocconfig` add `tabnine.prioriy: 50`

**Comment by Mestag** [comment]
you add that without quotation marks

**Comment by rjshrjndrn** [comment]
@Mestag Didn't get you.
