### ISSUE TITLE
Unable to configure TabNine

### ISSUE THREAD

**Issue by sQVe** [neoclide/coc-tabnine#12]
Hey :wave:,

I'm getting `coc-tabnine` to install and it downloads the `2.0.4` binary. The autocomplete works fine but I'm unable to properly configure it, license key / beta access etc. `CocCommand tabnine.openConfig` just gives me an empty JSON file and `TabNine::config` does nothing.

I'm very confused on how I'm supposed to configure TabNine / coc-tabnine. All help appreciated! :heart:

**Comment by sQVe** [comment]
@chemzqm ☝️🙏

**Comment by bfulop** [comment]
@sQVe, one thing that seems to work here is:

1. write `TabNine::config` then go back to normal mode (nothing happens)
2. enter insert mode again (after the letter `g`) and hit TAB (I have TAB set up as in the [setup example](https://github.com/neoclide/coc.nvim#example-vim-configuration) in the coc readme.

This opens the web interface to configure TabNine.

**Comment by sQVe** [comment]
@bfulop Awesome. I'll try this later today.

It would be nice to have something a bit more failsafe. A command to open the web interface or something similar.

**Comment by bfulop** [comment]
I guess it has to do something with the completion trigger between Vim/CoC/TabNine...

**Comment by sQVe** [comment]
@bfulop Your suggestion works fine. It would be nice if it was possible to omit the `TabNine Cloud is disabled for this directory. Type etc. etc` when in a non whitelisted directory. The suggestion meny becomes quite large with all that text.

Closing this issue as I got my answer.
