### ISSUE TITLE
Imcomplete completion

### ISSUE THREAD

**Issue by peng1999** [neoclide/coc-tabnine#15]
Sometimes tabnine gives the completion of a whole sentence, but coc only completes the first word of it.
![批注 2019-08-09 102944](https://user-images.githubusercontent.com/12483662/62749932-ea45a300-ba90-11e9-8c80-9917720d0867.png)

**Comment by bfulop** [comment]
I have the same issue. As a _temporary_ workaround, I noticed that if I select another completion, then move back to the one I want to expand, and then hit the DEL key, the whole sentence is inserted.

**Comment by chemzqm** [comment]
You have to confirm completion,since it's snippet

**Comment by bfulop** [comment]
@chemzqm, sorry for asking the obvious but how do you confirm the completion? 

If I press enter, it adds a new line...

**Comment by bfulop** [comment]
Ah I guess it's

```
inoremap <silent><expr> <cr> pumvisible() ? coc#_select_confirm() : 
                                           \"\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
```

from [Snippet completion readme](https://github.com/neoclide/coc.nvim/wiki/Using-snippets#snippet-completion)

**Comment by chemzqm** [comment]
It's documented in wiki
