### ISSUE TITLE
Conflict with coc-java

### ISSUE THREAD

**Issue by kongluoxing** [neoclide/coc-tabnine#21]
![tabnine-conflict-java](https://user-images.githubusercontent.com/2104457/64471477-aa9fd300-d184-11e9-87ae-82dd82decedf.gif)

1. type System
2. use `<c-j>` to select one provide by [LS]
3. press `<tab>`
4. there is trailing chars "yst" 

work as expected when remove coc-tabnine

using:
vim version: NVIM v0.4.0-2921-gf3cb52977
node version: v10.16.2
coc.nvim version: 0.0.74
os: mac

**Comment by chemzqm** [comment]
Should be problem of your language server, need check verbose output https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
