### ISSUE TITLE
How to open the config file of tabnine?

### ISSUE THREAD

**Issue by arstum** [neoclide/coc-tabnine#22]
Where and how to run "tabnine.openConfig" command?

**Comment by fannheyward** [comment]
`:CocCommand tabbing.openConfig`. Read coc.nvim wiki first.

**Comment by sQVe** [comment]
@arstum You can also open the default settings for `TabNine` by autocompleting `TabNine::config` in `vim`. This opens a browser window where you can configure `TabNine`.
