### ISSUE TITLE
Getting EACCES error when running CocCommand tabnine.openConfig

### ISSUE THREAD

**Issue by mcchrish** [neoclide/coc-tabnine#24]
```
[coc.nvim] error: Uncaught exception: Error: spawn /Users/mcchris/.config/coc/extensions/coc-tabnine-data/binaries/2.1.17/x86_64-apple-darwin/TabNine EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by sQVe** [comment]
@mcchrish What access does the actual binary have? Do you know when you installed the 2.1.17 binary? Does it only error when you open the CocConfig?

I'll try and see if I can reproduce it on my machine later today.

**Comment by sQVe** [comment]
@mcchrish I cannot reproduce this on my Linux system. Please provide answers to the above questions and any other information that might be relevant.

**Comment by mcchrish** [comment]
I may not be just following the instructions right. I've installed the plugin via Vim Plug https://github.com/mcchrish/dotfiles/blob/master/vim/.config/nvim/init.vim#L61. After that I try to run CocCommand tabnine.openConfig received that error. Error only happens when I run that command although I don't seem to get any completion too. Are there extra steps aside from installing the plugin?

**Comment by sQVe** [comment]
@mcchrish You should install the extension with `:CocInstall coc-tabnine`. Read the README for all the details.

**Comment by mcchrish** [comment]
I'm still getting the error even with the `:CocInstall coc-tabnine` method.

**Comment by sQVe** [comment]
@mcchrish What permissions does the binary have. `ls -l /path/to/binary`?

**Comment by mcchrish** [comment]
@sQVe I've checked and the binary doesn't seem to have execute permission. So manually add it (`chmod +x`). Unfortunately still doesn't work, only get a timeout error when trying to run CocCommand.

Then finally I reinstalled the plugin completely (deleting the `coc-tabnine-data` and reinstall) and now it works! It's probably similar to https://github.com/neoclide/coc-tabnine/issues/6 where the install was corrupted.

**Comment by reportaman** [comment]
I encountered the same problem today, and  manually adding permission (chmod +x) did the trick!

**Comment by hsequeda** [comment]
I solved the problem runing the command 'tabnine.updateTabNine'.

**Comment by linrongbin16** [comment]
same issue, tried three upper methods:
* manually remove `~/.config/coc/extension/coc-tabnine-data` and `~/.config/coc/extension/node_modules/coc-tabnine`, restart - not working
* `chmod +x ~/.config/coc/extension/coc-tabnine-data/binaries/4.0.6/x86-64-macos-darwin/TabNine` - not working
* `CocCommand tabnine.updateTabNine` - this one working!
