### ISSUE TITLE
Cannot open :Command tabnine.openConfig

### ISSUE THREAD

**Issue by nekowasabi** [neoclide/coc-tabnine#26]
hi.

I install coc.nvim and coc-tabnine and execute `CocCommand tabnine.openConfig`.
But cannot open TabNine's config(nothing response).

I tried Tabnine with deoplete.
It can use Tabnine.

Please teach me how to setting.

## env
OS : MacOS Mojave
NVIM v0.5.0-23-gafd576ee9

## minimal setting
``` 
if empty(glob('~/.config/nvim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall | source $MYVIMRC
endif

call plug#begin('~/.config/nvim/plugged')
Plug 'neoclide/coc.nvim', {'do': { -> coc#util#install()}}
call plug#end()
```

**Comment by sQVe** [comment]
@nekowasabi This is very likely due to a broken install. Remove the package fully and reinstall.

**Comment by nekowasabi** [comment]
@sQVe Thanks. I could solve this problem.
