### ISSUE TITLE
Specify custom TabNine version

### ISSUE THREAD

**Issue by tfachmann** [neoclide/coc-tabnine#27]
The current TabNine `version 2.1.20` consumes drastic amounts of CPU and RAM. When typing, it is always near 100% CPU and takes up about 1.5 GB of ram in a single file (As I just began using TabNine I am not sure how much usage is normal, but this seems to be too much)

This Issue is not new and seemed to occur repeatedly throughout the versions as seen in [this thread](https://github.com/zxqfl/TabNine/issues/43).

Is it be possible to specify which version of TabNine could be used?

**Comment by sQVe** [comment]
@tfachmann This is possible by downloading a selected binary and use `tabnine.binary_path` to specify its path. It is very unlikely that we will implement a way to automatically download a use a specific version.
