### ISSUE TITLE
High memory when using tabnine

### ISSUE THREAD

**Issue by vanphandinh** [neoclide/coc-tabnine#31]
<img width="656" alt="Screen Shot 2019-12-17 at 3 05 04 PM" src="https://user-images.githubusercontent.com/13887599/70976494-9e5dd700-20de-11ea-88ad-1c52876ae93f.png">
Tabnine is using too much memory. How can fix it?

**Comment by sQVe** [comment]
This is not related to this plugin but `TabNine` itself. There are plenty of issues like: https://github.com/zxqfl/TabNine/issues/183

One this that should lower the CPU and memory usage significantly is to disable `TabNine.local` by running `TabNine::config`.
