### ISSUE TITLE
spawn extentions/coc-tabnine-data/...../x86_64-unkown-linux-musl

### ISSUE THREAD

**Issue by 20jam** [neoclide/coc-tabnine#32]
Hello I have this problem ongoing everytime I open vim , first timeout then this.

Is there something I didn't instsll ?

Thanks

**Comment by sQVe** [comment]
You need to provide more detailed information and when the issues occurs.

Also, try reinstalling and removing directories related to `coc-tabnine`.

**Comment by 20jam** [comment]
Yes tried installing and reinstalling / wapping out dir, but still no use. Is there a dependence I need to install ?

**Comment by sQVe** [comment]
No. You should not have to install any dependency. You do need to provide logs on what the actual issue is though. There isn't much to go on here.

**Comment by 20jam** [comment]
Okay, there is two logs I'm geting:

When I do CoCommand tabnine.openConfig:
```
[coc.nvim] error: Uncaught exception: Error: spawn /home/a/.config/coc/extentions/coc-tabnine-data/binaries/2.1.22/x86_64-unknown-linux-musl/TabNine EACCES 
     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:19)
     at onErrorNT (internal/child_process.js:468:16)
     at processTickAndRejections (internal/process/task_queues.js:84:21)
```

And When I'm editing, I get time out errors.

**Comment by sQVe** [comment]
Is there a binary at `/home/a/.config/coc/extentions/coc-tabnine-data/binaries/2.1.22/x86_64-unknown-linux-musl/TabNine` and what permissions does it have?

**Comment by 20jam** [comment]
```bash
912 -rw-r--r-- 1 beta wheel 932961 Dec 24 05:29 TabNine
```

**Comment by sQVe** [comment]
Well its not strange that your getting `EACCES` when the binary does not have any execute permissions. Try running `chmod 755` on the binary.

Something must have failed in the install chain when setting permissions.

**Comment by 20jam** [comment]
So I did `chmod 755` no there is not errors from CocCommand tabninte.openConfig, however the config doesn't open and for the timeout error I still get it

**Comment by sQVe** [comment]
This issue must be because of a failed binary download. Remove everything in `coc-tabnine-data`, uninstall `coc-tabnine` and then reinstall again.

**Comment by 20jam** [comment]
After Deleteing `coc-tabnine-data` and running `CocUninstall coc-tabnine-data` and reinstalling it , I got the same message as before from running CoCommand tabnine.openConfig:
```
[coc.nvim] error: Uncaught exception: Error: spawn /home/a/.config/coc/extentions/coc-tabnine-data/binaries/2.1.22/x86_64-unknown-linux-musl/TabNine EACCES 
     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:19)
     at onErrorNT (internal/child_process.js:468:16)
     at processTickAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by sQVe** [comment]
Do you have a `tabnine_config.json` in `$HOME/.config/TabNine`?

**Comment by 20jam** [comment]
No I do not

**Comment by sQVe** [comment]
What happens if you type in `TabNine::config` in a buffer and after it trigger autocomplete? It should open a tab in your browser where you can configure TabNine.

**Comment by 20jam** [comment]
No nothing, I've typed TabNine::config inside the buffer but nothing happend

**Comment by sQVe** [comment]
Closing this as it's been inactive for some time.

**Comment by Mdsp9070** [comment]
I'm having same issue! Tried to reinstall but no effect.
```shell
## versions                                                                    
vim version: NVIM v0.4.4
node version: v14.9.0
coc.nvim version: 0.0.78-0ff42027ff
coc.nvim directory: /home/mdsp/nvim/plugged/coc.nvim
term: xterm-256color
platform: linux (Manjaro GNOME) 
```

**Comment by Laptop765** [comment]
I just ran into a similar issue and it turns out when I was setting up my machine, `vim` ran as `root` when it installed `coc-tabnine` and permissions are all wrong.

While in `$HOME` run: `find | grep -i tabnine | xargs ls -la` and make sure all of the user/group permissions are correct (non-root.)  After deleting all of the incorrectly permissioned files I was up and running again.

Locations I had to delete (please double check for data loss before blindly deleting!):
- `./local/share/TabNine`
- `./config/TabNine`
- `./config/coc/extensions/coc-tabnine-data`

**Comment by ayoubelmhamdi** [comment]
for me i'm go to this directory
```
cd ~/.config/coc/extensions/coc-tabnine-data/binaries/3.3.96/aarch64-unknown-linux-musl/
```
and i'm downloas manuel :
```
curl -LO https://update.tabnine.com/bundles/3.3.96/aarch64-unknown-linux-musl/TabNine
```
and it's solved
