### ISSUE TITLE
can't tab complete

### ISSUE THREAD

**Issue by theonlygusti** [neoclide/coc-tabnine#35]
I want to use tab to cycle suggestions and to complete, so I copypasted coc.nvim's sample code into my init.vim. Relevant section:

```vim
" Use tab for trigger completion with characters ahead and navigate.
" Use command ':verbose imap <tab>' to make sure tab is not mapped by other plugin.
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction
```

Pressing tab completes all the `[A]` suggestions, but not the `[TN]` ones.

**Comment by chemzqm** [comment]
Use `:CocList sources` to get all activated sources.

**Comment by theonlygusti** [comment]
@chemzqm the sources are

```
  * tabnine [TN] 99                                                                                                     
  * jedi [JD] 99 python                                                    
  * file [F] 10
  * buffer [B] 1 
  * around [A] 1
```

are you able to help me though?

Why doesn't tab completion work?

**Comment by theonlygusti** [comment]
I just noticed, tab completion does work, but only up to the last word character; as soon as hitting a space, or a bracket or paranthesis, the tab completion won't substitute.

If I typed `__add` and the suggestion is `__add__(self,)~ S 33% [TN]`, pressing tab only fills `__add__` and then stops. Pressing tab again undoes that, reverting to what I had typed before `__add`.

**Comment by chemzqm** [comment]
@theonlygusti you have to confirm completion https://github.com/neoclide/coc.nvim/wiki/Completion-with-sources#improve-the-completion-experience

**Comment by theonlygusti** [comment]
@chemzqm how do I make it confirm completion without exiting the pum https://github.com/neoclide/coc.nvim/issues/1536

**Comment by theonlygusti** [comment]
Or, how can I make coc-tabnine only provide completions and not snippets?

**Comment by chemzqm** [comment]
> @chemzqm how do I make it confirm completion without exiting the pum [neoclide/coc.nvim#1536](https://github.com/neoclide/coc.nvim/issues/1536)

It's not possible.
