### ISSUE TITLE
Make suggestions normal completions and not snippets

### ISSUE THREAD

**Issue by theonlygusti** [neoclide/coc-tabnine#36]
According to #35 the reason coc-tabnine can't be previewed and completed using the same key is because the suggestions are for snippets.

It would be better if they weren't snippets.

**Comment by chemzqm** [comment]
If they weren't snippets they could be less useful, you can always use `<C-y>` to confirm completion instead just use `<tab>` which is bad idea IMO.

**Comment by theonlygusti** [comment]
Why would they be less useful if they weren't snippets?

**Comment by sQVe** [comment]
The whole idea behind TabNine is to the to complete whole lines or as much as possible, intelligently. To remove the snippet functionality would disable this feature.

**Comment by theonlygusti** [comment]
> The whole idea behind TabNine is to the to complete whole lines or as much as possible, intelligently. To remove the snippet functionality would disable this feature.

why?

Why the PUM shows tab nine options, they are _always_  things like

```
f(first, second)
public void Function3(
new List<Type>();
```

They never have empty placeholders in them, as I'd expect snippets to.

**Comment by sersorrel** [comment]
I also don't understand this.

What benefit does marking the tabnine completions as "snippets" actually have? As far as I can tell, all it does is mean that the completion doesn't happen until you press `<cr>`, as well as put the cursor in a weird place afterwards.

**Comment by theonlygusti** [comment]
Please can you teach us how to configure coc-tabnine to insert the entire suggestion text on tab press?

**Comment by theonlygusti** [comment]
@sQVe 

> The whole idea behind TabNine is to the to complete whole lines or as much as possible, intelligently.

_Because_  tabnine always provides complete suggestions, why does coc-tabnine only fill in part of the suggestion instead of all of it?
