### ISSUE TITLE
coc_nvim_1.fetch is not a function

### ISSUE THREAD

**Issue by lourenci** [neoclide/coc-tabnine#4]
The following error happens just after the coc-tabnine installation.

[coc.nvim] Installed extension: coc-tabnine
[coc.nvim] Error on active extension coc-tabnine: TypeError: coc_nvim_1.fetch is not a function

**Comment by chemzqm** [comment]
use latest release branch of coc.nvim

**Comment by lourenci** [comment]
It is the 0.72 version, isn't it?

![image](https://user-images.githubusercontent.com/2339362/60973391-95cace80-a2fe-11e9-99c1-90f4ed997b44.png)

**Comment by chemzqm** [comment]
22daa03a is tag release, remove `tag: '*'` from Plug command.

**Comment by lourenci** [comment]
The same problem. I've removed the `tag` from Plug command and installed again, even uninstalled coc, deleted all related coc file in `~./config` and installed again.

**Comment by chemzqm** [comment]
Use `  Plug 'neoclide/coc.nvim', {'branch': 'release'}` and checkout the version by `:CocInfo`
