### ISSUE TITLE
TabNine::version not working

### ISSUE THREAD

**Issue by lovesegfault** [neoclide/coc-tabnine#5]
When trying to perform the version test by typing in `TabNine::version` I get `TabNine` to complete, but not `version` and the version info is not displayed.

Moreover, my config shows version 1.0.10, which is outdated.

**Comment by chemzqm** [comment]
You might using old version of coc-tabnine.

**Comment by lovesegfault** [comment]
`CocList` says I'm using 1.1.5:

![image](https://user-images.githubusercontent.com/7243783/61146209-5501bf80-a48e-11e9-88aa-399ad82d8d8f.png)

**Comment by chemzqm** [comment]
Try `:CocCommand tabnine.openConfig`

**Comment by lovesegfault** [comment]
That successfully opens the config, but I'm not sure what else it should accomplish

**Comment by chemzqm** [comment]
Check doc of tabnine.
