### ISSUE TITLE
error at launch

### ISSUE THREAD

**Issue by danielfalbo** [neoclide/coc-tabnine#53]
As soon as I open neovim and start typing something, I get this error:
![Screenshot 2020-12-08 at 07 40 29](https://user-images.githubusercontent.com/39460524/101449311-d6ca7680-3928-11eb-8769-bbff5a556e61.png).

```
vim version: NVIM v0.5.0-7e0e0782a
node version: v15.3.0
coc.nvim version: 0.0.79-9eb7e5b2ae
coc-tabnine version: 1.2.3
```

**Comment by danielfalbo** [comment]
I tried to `chmod +x coc-tabnine-data/binaries/3.2.28/x86_64-apple-darwin/*` and now I do not get the error anymore but `:CocCommand tabnine.openConfig` does not do anything and I do not seen any completion hint from TabNine when I start typing code in python. I tried multiple times to uninstall coc-tabnine and reinstall it.

**Comment by UnknowsBetter** [comment]
so do I， can not open a tab nine config file. And always reports time out after 5000ms

😭

**Comment by Boshen** [comment]
I managed to fix this by manually downloading, extracting, and `chmod 755` all the files by following the source 
https://github.com/neoclide/coc-tabnine/blob/master/src/tabnine.ts#L108-L120

**Comment by tejasvi** [comment]
For me, `:CocCommand tabnine.updateTabNine` then `:CocRestart` worked.
