### ISSUE TITLE
Attempting to install via Yarn leads to an infinite loop

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [neoclide/coc-tabnine#55]
So, I've got `coc-tabnine` installed via `vim-plug`:

    Plug 'neoclide/coc-tabnine', {'do': 'yarn install --frozen-lockfile'}

Unfortunately, attempting to actually run `yarn install --frozen-lockfile` yields an infinite loop, where I'm repeatedly asked by `npx webpack` whether I want to install `webpack-cli`:

https://asciinema.org/a/qSblKmGWlFvBNAHBxzeXToWzG

Not sure what's up with this, hope this report is helpful. Perhaps I am doing something wrong!

**Comment by ELLIOTTCABLE** [comment]
Notably, it looks like the other `coc` plugins I just tested, use simply `webpack` as the command, instead of `npx webpack` — the `npx` may be redundant in the [npm `"scripts"` context](https://docs.npmjs.com/cli/v6/using-npm/scripts). <3

**Comment by chemzqm** [comment]
`npx webpack` not used any more
