### ISSUE TITLE
Is it possible to have <C-J> to accept intead default <C-Y>?

### ISSUE THREAD

**Issue by Lakshamana** [neoclide/coc-tabnine#70]
Title says it all, it would be nice and awesome to configure this hotkey. Nice project, btw).

I was expecting to set it like this:
```vim
let g:tabnine#accept_suggestion='<c-[ANY KEY HERE]>'
```

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc.nvim/wiki/Completion-with-sources#use-cr-to-confirm-completion
