### ISSUE TITLE
Autocomplete text not inserted into the buffer

### ISSUE THREAD

**Issue by lukepass** [neoclide/coc-tabnine#79]
Hello and thanks for the plugin!
I purchased the license but I have a problem with the plugin. Why is the text not inserted into the buffer but I have to press "Enter" or "Tab" to accept it?

I expected the part `('target_path`) to be inserted as well into the buffer.

Thanks.

![image](https://user-images.githubusercontent.com/6429961/168838164-c4ac4218-a21a-4913-ac0d-ed4e70dcd4b6.png)

**Comment by chemzqm** [comment]
`:h coc-config-suggest-invalidInsertCharacters` or confirm completion.

**Comment by chemzqm** [comment]
No, confirm completion is recommended.

**Comment by lukepass** [comment]
Ok, thanks! My current Ctrl-Y is mapped to emmet and other things and so accepting with Ctrl-Y is not available. Di you know how can I remap it to accept the entry?

Thanks again!

**Comment by chemzqm** [comment]
Read wiki https://github.com/neoclide/coc.nvim/wiki/Completion-with-sources

**Comment by lukepass** [comment]
That's it! For all the people who have the same problem this is the relevant part:

```
inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
```

If you want to complete the whole line just add this to the coc.nvim config:

```
"suggest.invalidInsertCharacters" : ["("]
```

@chemzqm I already read the wiki but many days before having this problem :)

Thanks.
