### ISSUE TITLE
Support new TabNine 2.0.2 

### ISSUE THREAD

**Issue by pawelduda** [neoclide/coc-tabnine#8]
[Deep TabNine](https://tabnine.com/blog/deep)

This plugin only supports version 1.x, even when I attempt to force an update.

If you need any help with this, perhaps I can be useful here - let me know.

**Comment by bfulop** [comment]
@pawelduda, I'm using coc-tabnine as well, and when I type `TabNine::version` it shows version `2.0.2`. I'm not 100% sure though that this means latest available version or the locally installed version number.

<img width="188" alt="tabnine-version" src="https://user-images.githubusercontent.com/1718128/61933993-91054c00-af87-11e9-8da2-d71a434e9fda.png">

**Comment by chemzqm** [comment]
It's locally installed version number

**Comment by bfulop** [comment]
Thanks @chemzqm, yes I can confirm, just managed to get the TabNine Cloud service going! 🎉

**Comment by sQVe** [comment]
`coc-tabnine` has support for *Deep TabNine*. If you're having troubles I suggest that you fully reinstall the extension. I'm currently running `2.1.17`, with both Cloud and Local enabled.

You can open the config by either writing and autocompleting `TabNine::config` or `:CocCommand tabnine.openConfig`. 

Closing.
