### ISSUE TITLE
"suggest. noselect": false is not working

### ISSUE THREAD

**Issue by avriltank** [neoclide/coc-tabnine#9]
I set "suggest. noselect": **false**, but coc-tabning always **automatically selects the first item**!
 Is there anything wrong with my settings? **Thank you**

**Comment by avriltank** [comment]
sorry ，I set "suggest. noselect": true, but coc-tabnine always automatically selects the first item!
Is there anything wrong with my settings? Thank you

**Comment by chemzqm** [comment]
It's `suggest.enablePreselect` feature, you need disable it.

**Comment by avriltank** [comment]
thanks，it is ok



------------------ 原始邮件 ------------------
发件人: "Qiming zhao"<notifications@github.com>;
发送时间: 2019年7月28日(星期天) 晚上10:46
收件人: "neoclide/coc-tabnine"<coc-tabnine@noreply.github.com>;
抄送: "爱我别走"<chenfa1@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [neoclide/coc-tabnine] "suggest. noselect": false is not working(#9)




It's suggest.enablePreselect feature, you need disable it.
